### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [MonsterCrew/Three_D_Change_Detection#1]
The links for the issues page redirects to the repository.

**Comment by jsbates** [comment]
I have updated the issue tracking link.

**Comment by jsbates** [comment]
Thank you for the correction.

**Comment by pcav** [comment]
From the plugin website http://plugins.qgis.org/plugins/Three_D_Change_Detection-master/ I still see the wrong link.

**Comment by pcav** [comment]
confirmed
